### 初始化

In [12]:
from jqdatasdk import finance, query
import jqdatasdk
import time
import copy
jqdatasdk.auth('17675677591', 'Keeyu.cc.9')
def has_spare() -> bool:
    data = jqdatasdk.get_query_count()
    print(data)
    return data['spare'] > 0

In [2]:
# 统计次数
has_spare()

{'total': 10000000, 'spare': 10000000}

True

In [4]:
# 所以交易日
jqdatasdk.get_all_trade_days()

array([datetime.date(2005, 1, 4), datetime.date(2005, 1, 5),
       datetime.date(2005, 1, 6), ..., datetime.date(2023, 11, 9),
       datetime.date(2023, 11, 10), datetime.date(2023, 11, 13)],
      dtype=object)

In [20]:
# 范围交易日
jys=jqdatasdk.get_trade_days(end_date='2021-01-01')
len(jys)

208

In [17]:

# 最新交易日
new_day = jqdatasdk.get_trade_days(count=1)
new_day[0]

datetime.date(2021, 12, 2)

In [9]:
bk=jqdatasdk.get_industries(name='sw_l1', date=time.strftime(
    "%Y-%m-%d", time.localtime()))

In [29]:
print(bk)

         name start_date
801740  国防军工I 2014-02-21
801020    采掘I 2004-02-10
801110  家用电器I 2004-02-10
801160  公用事业I 2004-02-10
801770    通信I 2014-02-21
801010  农林牧渔I 2004-02-09
801120  食品饮料I 2004-02-10
801750   计算机I 2014-02-21
801050  有色金属I 2004-02-10
801890  机械设备I 2014-02-21
801170  交通运输I 2004-02-10
801710  建筑材料I 2014-02-21
801780    银行I 2014-02-21
801040    钢铁I 2004-02-10
801130  纺织服装I 2004-02-10
801880    汽车I 2014-02-21
801180   房地产I 2004-02-10
801230    综合I 2004-02-10
801760    传媒I 2014-02-21
801200  商业贸易I 2004-02-10
801140  轻工制造I 2004-02-10
801720  建筑装饰I 2014-02-21
801080    电子I 2004-02-10
801790  非银金融I 2014-02-21
801030    化工I 2004-02-10
801210  休闲服务I 2004-02-10
801730  电气设备I 2014-02-21
801150  医药生物I 2004-02-10

In [40]:
for index, _ in bk.iterrows():
    print(index)
    break

801740

In [ ]:
for index, row in bk.iterrows():
    print (index,row["name"], row["start_date"])

In [45]:
df = finance.run_query(query(finance.SW1_DAILY_PRICE).filter(
    finance.SW1_DAILY_PRICE.code == '801080').order_by(finance.SW1_DAILY_PRICE.date.desc()).limit(10))
df

,id,date,code,name,open,high,low,close,volume,money,change_pct
0,1898452,2021-11-12,801080,电子元器件,5341.02,5396.08,5329.11,5389.94,5.959688e+09,1.235867e+11,0.50
1,1898396,2021-11-11,801080,电子元器件,5255.64,5403.05,5255.30,5363.00,6.592195e+09,1.409070e+11,1.52
2,1898340,2021-11-10,801080,电子元器件,5236.54,5297.43,5221.22,5282.58,5.944623e+09,1.214427e+11,0.54
3,1898284,2021-11-09,801080,电子元器件,5177.04,5261.60,5152.44,5254.41,4.861564e+09,1.098448e+11,1.35
4,1898228,2021-11-08,801080,电子元器件,5199.36,5199.36,5177.38,5184.58,5.000426e+09,1.119545e+11,-0.75
5,1898172,2021-11-05,801080,电子元器件,5236.67,5286.87,5223.92,5223.92,5.966132e+09,1.307270e+11,0.38
6,1898116,2021-11-04,801080,电子元器件,5149.66,5213.39,5145.48,5204.19,4.888097e+09,1.128904e+11,1.58
7,1898060,2021-11-03,801080,电子元器件,5152.85,5181.85,5076.10,5123.18,4.891734e+09,1.042405e+11,-0.37
8,1898004,2021-11-02,801080,电子元器件,5125.25,5204.47,5100.46,5142.35,5.911875e+09,1.359448e+11,0.56
9,1897696,2021-11-01,801080,电子元器件,5008.48,5123.58,5008.08,5113.72,5.638481e+09,1.214712e+11,2.17

In [44]:
for index, row in df.iterrows():
    print(dict(row))
    break

{'id': 1898468, 'date': datetime.date(2021, 11, 12), 'code': '801010', 'name': '农林牧渔', 'open': 3627.83, 'high': 3705.13, 'low': 3627.83, 'close': 3678.35, 'volume': 1883851460.0, 'money': 23099399855.0, 'change_pct': 1.39}

In [6]:
ri = jqdatasdk.get_bars('000001.XSHE', count=1, fields=[
                   'date', 'open', 'close', 'high', 'low', 'volume', 'money'], unit='1d', include_now=True, df=True)
ri

         date   open  close   high    low      volume         money
0  2021-12-01  17.43  17.64  17.77  17.37  70692519.0  1.243667e+09

In [21]:
ri.iloc[1]

date         2021-06-18
open              23.13
close             22.65
high              23.28
low               22.39
volume       69409930.0
money     1574437729.58
Name: 1, dtype: object

In [36]:
# fenxing
def calc_base(org):
    list=[]
    len_ = len(org)
    if len_<= 1:
        return list
    index=1
    while index+1 < len_:
        find_fenx(org,index,list)
        index+=1
    return filter_fenx(list)

def find_fenx(org, index,list):
    if org.iloc[index]['low'] < org.iloc[index-1]['low'] and org.iloc[index]['low'] < org.iloc[index+1]['low']:
        data=dict(org.iloc[index])
        data['type']='high'
        data['index']=index
        list.append(data)
    elif org.iloc[index]['high'] > org.iloc[index-1]['high'] and org.iloc[index]['high'] > org.iloc[index+1]['high']:
        data = dict(org.iloc[index])
        data['type'] = 'low'
        data['index']=index
        list.append(data)


def filter_fenx(list):
    last_obj={'type':'init','index':-99,'high':-99999,'low':99999}
    clean_1=[]
    for i in list:
        if i['type']==last_obj['type']:
            if i['type']=='high' and i['high']>last_obj['high']:
                last_obj=i
            elif i['type'] == 'low' and i['low'] < last_obj['low']:
                last_obj=i
        elif i['index']-last_obj['index']>=3:
            if last_obj['type']!='init':
                clean_1.append(copy.deepcopy(last_obj))
            last_obj=i
    return clean_1

calc_base(ri)

[{'date': datetime.date(2021, 6, 24),
  'open': 23.03,
  'close': 23.08,
  'high': 23.12,
  'low': 22.68,
  'volume': 39028349.0,
  'money': 894502108.58,
  'type': 'high',
  'index': 5},
 {'date': datetime.date(2021, 7, 7),
  'open': 22.68,
  'close': 22.55,
  'high': 23.05,
  'low': 22.5,
  'volume': 46894487.0,
  'money': 1063910095.83,
  'type': 'low',
  'index': 14},
 {'date': datetime.date(2021, 7, 14),
  'open': 21.0,
  'close': 20.76,
  'high': 21.0,
  'low': 20.41,
  'volume': 84795055.0,
  'money': 1755810875.16,
  'type': 'high',
  'index': 19},
 {'date': datetime.date(2021, 8, 3),
  'open': 17.99,
  'close': 17.89,
  'high': 18.15,
  'low': 17.66,
  'volume': 89694857.0,
  'money': 1609422575.43,
  'type': 'low',
  'index': 33},
 {'date': datetime.date(2021, 8, 6),
  'open': 17.55,
  'close': 17.86,
  'high': 17.9,
  'low': 17.45,
  'volume': 56745413.0,
  'money': 1005870948.8,
  'type': 'high',
  'index': 36},
 {'date': datetime.date(2021, 8, 11),
  'open': 19.99,
  'close': 19.81,
  'high': 20.58,
  'low': 19.7,
  'volume': 104830844.0,
  'money': 2104975144.53,
  'type': 'low',
  'index': 39},
 {'date': datetime.date(2021, 8, 18),
  'open': 19.67,
  'close': 20.62,
  'high': 21.2,
  'low': 19.55,
  'volume': 133273216.0,
  'money': 2732213549.09,
  'type': 'high',
  'index': 44},
 {'date': datetime.date(2021, 9, 2),
  'open': 18.0,
  'close': 18.4,
  'high': 18.78,
  'low': 17.8,
  'volume': 242260354.0,
  'money': 4454545280.06,
  'type': 'low',
  'index': 55},
 {'date': datetime.date(2021, 9, 9),
  'open': 19.11,
  'close': 19.0,
  'high': 19.15,
  'low': 18.8,
  'volume': 73950585.0,
  'money': 1399536020.5,
  'type': 'high',
  'index': 60},
 {'date': datetime.date(2021, 9, 15),
  'open': 19.31,
  'close': 19.52,
  'high': 20.99,
  'low': 19.19,
  'volume': 84161841.0,
  'money': 1639298361.44,
  'type': 'low',
  'index': 64},
 {'date': datetime.date(2021, 9, 22),
  'open': 17.87,
  'close': 17.98,
  'high': 18.05,
  'low': 17.42,
  'volume': 147336521.0,
  'money': 2616707242.58,
  'type': 'high',
  'index': 67},
 {'date': datetime.date(2021, 9, 29),
  'open': 17.86,
  'close': 18.15,
  'high': 18.44,
  'low': 17.71,
  'volume': 123012175.0,
  'money': 2225416488.14,
  'type': 'low',
  'index': 72},
 {'date': datetime.date(2021, 10, 14),
  'open': 19.59,
  'close': 19.21,
  'high': 19.92,
  'low': 18.89,
  'volume': 84298987.0,
  'money': 1623970431.0,
  'type': 'high',
  'index': 78},
 {'date': datetime.date(2021, 10, 22),
  'open': 20.16,
  'close': 20.04,
  'high': 20.59,
  'low': 19.8,
  'volume': 113496363.0,
  'money': 2287284921.47,
  'type': 'low',
  'index': 84}]

In [5]:
for index, row in ri.iterrows():
    print(dict(row))
    break

{'date': datetime.date(2021, 11, 11), 'open': 17.35, 'close': 18.35, 'high': 18.43, 'low': 17.32, 'volume': 208472900.0, 'money': 3752413858.84}

In [5]:
res = jqdatasdk.get_all_securities(types=['etf','stock','lof'], date=None)
res

            display_name  name start_date   end_date   type
000001.XSHE         平安银行  PAYH 1991-04-03 2200-01-01  stock
000002.XSHE          万科A   WKA 1991-01-29 2200-01-01  stock
000004.XSHE         国华网安  GHWA 1990-12-01 2200-01-01  stock
000005.XSHE         ST星源  STXY 1990-12-10 2200-01-01  stock
000006.XSHE         深振业A  SZYA 1992-04-27 2200-01-01  stock
...                  ...   ...        ...        ...    ...
688799.XSHG         华纳药厂  HNYC 2021-07-13 2200-01-01  stock
688800.XSHG          瑞可达   RKD 2021-07-22 2200-01-01  stock
688819.XSHG         天能股份  TNGF 2021-01-18 2200-01-01  stock
688981.XSHG         中芯国际  ZXGJ 2020-07-16 2200-01-01  stock
689009.XSHG         九号公司  JHGS 2020-10-29 2200-01-01  stock

[5787 rows x 5 columns]

In [11]:
for index, row in res.iterrows():
    print(row['display_name'])
    print(index)
    break

平安银行
000001.XSHE

display_name
name
start_date
end_date
type